# Generated by Django 5.1.7 on 2025-03-30 13:59

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
